import 'dart:typed_data';

import 'package:convert/convert.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:subterfuge/shared/slip39_facade.dart';

void main() {
  group('Slip39Facade.combine — reference vectors', () {
    test('recovers the README dataset (2/3 shares, no passphrase)', () {
      // From README.md: 2 of the 3 shares recover the documented 512-bit seed.
      const shares = [
        'voting leader beard leader academic tidy vegan temple mansion prize sharp lobe capital umbrella tactics network window traffic perfect width glimpse armed center rebuild earth declare privacy corner fantasy walnut keyboard blimp bedroom superior weapon ending legs prepare making sister rival peasant estimate mayor club realize avoid tactics blessing campus slap document race engage step marvel class frozen percent',
        'voting leader ceramic leader acid liberty alarm invasion adorn script python desert clothes increase mandate deny tenant chubby body prune news photo writing bedroom careful dish alpha miracle webcam eraser briefing location elder pregnant package modern justice rainbow slush spark memory duke stadium season transfer cultural echo heat fantasy geology bulb merit detect wrist webcam ocean cultural breathe hospital',
      ];
      const expectedSeed =
          'b6a6d8921942dd9806607ebc2750416b289adea669198769f2e15ed926c3aa92bf88ece232317b4ea463e84b0fcd3b53577812ee449ccc448eb45e6f544e25b6';

      final recovered = Slip39Facade.combine(shares: shares, passphrase: '');

      expect(hex.encode(recovered), expectedSeed);
    });

    test('recovers a cross-implementation vector generated by the Python '
        '`shamir-mnemonic` reference implementation (2/3 shares, '
        'iteration_exponent=1, passphrase "TREZOR")', () {
      // Generated with:
      //   generate_mnemonics(2, [(1,1),(1,1),(1,1)],
      //     bytes.fromhex("00112233445566778899aabbccddeeff"),
      //     passphrase=b"TREZOR", iteration_exponent=1)
      // and verified to round-trip through both the Python reference
      // implementation and this Dart implementation during the audit.
      const shares = [
        'trust cleanup beard leader analysis dance hand prayer hearing domain cubic dismiss submit reunion daughter evaluate undergo family welfare lying',
        'trust cleanup ceramic leader civil round repeat formal course verify union wisdom cinema demand revenue leaf priest faint custody emperor',
      ];
      const expectedSecret = '00112233445566778899aabbccddeeff';

      final recovered = Slip39Facade.combine(
        shares: shares,
        passphrase: 'TREZOR',
      );

      expect(hex.encode(recovered), expectedSecret);
    });
  });

  group('Slip39Facade round-trip', () {
    Uint8List secretOf(String hexString) =>
        Uint8List.fromList(hex.decode(hexString));

    test('share then combine recovers the original secret (no passphrase)', () {
      const secretHex = '0123456789abcdef0123456789abcdef';
      final secret = secretOf(secretHex);

      final shares = Slip39Facade.share(
        shares: 5,
        threshold: 3,
        masterSecret: secret,
        passphrase: '',
      );

      expect(shares.length, 5);

      final recovered = Slip39Facade.combine(
        shares: shares.sublist(0, 3),
        passphrase: '',
      );

      expect(hex.encode(recovered), secretHex);
    });

    test(
      'share then combine recovers the original secret (with passphrase)',
      () {
        const secretHex = 'fedcba9876543210fedcba9876543210';
        final secret = secretOf(secretHex);
        const passphrase = 'correct horse battery staple';

        final shares = Slip39Facade.share(
          shares: 3,
          threshold: 2,
          masterSecret: secret,
          passphrase: passphrase,
        );

        // Any 2-of-3 subset must recover the same secret.
        final recoveredA = Slip39Facade.combine(
          shares: [shares[0], shares[1]],
          passphrase: passphrase,
        );
        final recoveredB = Slip39Facade.combine(
          shares: [shares[1], shares[2]],
          passphrase: passphrase,
        );

        expect(hex.encode(recoveredA), secretHex);
        expect(hex.encode(recoveredB), secretHex);
      },
    );

    test('a wrong passphrase does not throw but yields a different secret', () {
      // SLIP-39's plausible-deniability property: decrypting with the wrong
      // passphrase silently succeeds and returns a *different*, still
      // valid-looking secret rather than failing loudly. This test pins
      // down that behavior so a future library upgrade that changes it is
      // caught, and documents why the app displays a verification warning
      // (see ShowSecretPage).
      const secretHex = '00112233445566778899aabbccddeeff';
      final secret = secretOf(secretHex);

      final shares = Slip39Facade.share(
        shares: 3,
        threshold: 2,
        masterSecret: secret,
        passphrase: 'correct-passphrase',
      );

      final recovered = Slip39Facade.combine(
        shares: [shares[0], shares[1]],
        passphrase: 'wrong-passphrase',
      );

      expect(hex.encode(recovered), isNot(secretHex));
    });

    test('threshold of 1 recovers the secret from any single share', () {
      const secretHex = '11112222333344445555666677778888';
      final secret = secretOf(secretHex);

      final shares = Slip39Facade.share(
        shares: 3,
        threshold: 1,
        masterSecret: secret,
        passphrase: '',
      );

      for (final share in shares) {
        final recovered = Slip39Facade.combine(shares: [share], passphrase: '');
        expect(hex.encode(recovered), secretHex);
      }
    });
  });

  group('Slip39Facade async (compute/isolate) variants', () {
    Uint8List secretOf(String hexString) =>
        Uint8List.fromList(hex.decode(hexString));

    test(
      'shareAsync/combineAsync round-trip the same result as the sync API',
      () async {
        const secretHex = 'deadbeefdeadbeefdeadbeefdeadbeef';
        final secret = secretOf(secretHex);
        const passphrase = 'isolate-roundtrip';

        final shares = await Slip39Facade.shareAsync(
          shares: 4,
          threshold: 2,
          masterSecret: secret,
          passphrase: passphrase,
        );

        expect(shares.length, 4);

        final recovered = await Slip39Facade.combineAsync(
          shares: [shares[1], shares[3]],
          passphrase: passphrase,
        );

        expect(hex.encode(recovered), secretHex);
      },
    );
  });
}
