// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:subterfuge/shared/errors.dart';

// Will be generated by dart_mappable
part 'state.mapper.dart';

@MappableClass()
class ShareSecretState with ShareSecretStateMappable {
  final bool isLoading;
  final List<String> shares;
  final AppError? error;

  ShareSecretState({
    this.isLoading = false,
    this.shares = const [],
    this.error,
  });
}
